#!/usr/local/bin/perl


print "Content-type: text/html\n\n";
print "<html>\n<head>\n<title>Your First Perl Script</title>\n</head>\n";
print "<body bgcolor=\"FFFFFF\">";
print "<p>";
print "<center>";
print "<font face=\"arial\" size=\"2\">";
print "<h2>Your First Perl Script</h2>\n\n";
print "<hr noshade width=80%>\n";
print "<p>";
print "<table cellspace=\"5\" cellpadding=\"5\" width=\"500\" nowrap>";
print "<tr>";
print "<td>";
print "<font face=\"arial\" size=\"2\">";
print "<img vspace=\"5\" valign=\"top\" align=\"right\" src=\"http://testboo.it.earthlink.net/eln-images/blink_pointing.gif\">";
print "<b><i>W</i></b>elcome <b><em>\"$ENV{REMOTE_HOST}\"</em></b>!!!";
print "<p>";
print "   My name is <i>Blinky</i> and I'm here to introduce you to";
print " your first CGI script.  First, let me tell you some information.";
print "  Your current IP address is <b><i>\"$ENV{'REMOTE_ADDR'}\"</i></b> and";
print "  you came to this page from this URL:  <b><i>\"$ENV{'HTTP_REFERER'}\"</i></b>";
print "  The name of this script is <b><em>\"$ENV{'SCRIPT_NAME'}\"</em></b> and";
print " it is written in Perl, the most popular language used in writing CGI scripts.";
print "<p>";
print "Though this script is fairly simple, it gives you an idea of the many";
print " useful tasks that can be accomplished by using  CGI scripts.";
print "<p>";
print "Your Perl scripts need to be uploaded in the \"cgi\" directory of your";
print " home directory.  It is very important to note that Perl scripts must ";
print "be uploaded in text/ASCII mode.  To activate your script, send a message ";
print "to <a href=\"mailto:websupport\@earthlink.net\"><i>websupport\@earthlink.net</i></a>";
print "<p align=\"right\">";
print "Thanks for visiting,";
print "<br><br>";
print "--- <i><b>Blinky</b></i>";
print "</p><br>";
print "<center>";
print "<a href=\"$ENV{'HTTP_REFERER'}\">Previous Page</a>";
print "</center>";
print "</font>";
print "</td>";
print "</tr>";
print "</table>";
print "</center>";
print "<p>";
print "<hr noshade width=80%>\n";
print "</center>";
print "</body>";
print "</html>";
